name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches_ignore: []

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Linting
      uses: snakemake/snakemake-github-action@v1.22.0
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--configfile .test/configs/config_se.yaml --lint"

  run-workflow:
    runs-on: ubuntu-latest
    needs:
      - linting
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Test workflow (multi)
      uses: ezherman/snakemake-github-action@5027c0e706ada924ab91e0501bd92185fc98de3c
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--configfile .test/configs/config_multi.yaml --use-conda --show-failed-logs --cores 2 --conda-cleanup-pkgs cache"
    - name: Test workflow (single-end)
      uses: ezherman/snakemake-github-action@5027c0e706ada924ab91e0501bd92185fc98de3c
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--configfile .test/configs/config_se.yaml --use-conda --show-failed-logs --cores 2 --conda-cleanup-pkgs cache"
    - name: Test workflow (paired-end)
      uses: ezherman/snakemake-github-action@5027c0e706ada924ab91e0501bd92185fc98de3c
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--configfile .test/configs/config_pe.yaml --use-conda --show-failed-logs --cores 2 --conda-cleanup-pkgs cache"
